add-friends-likes на ревью (ТЗ-10)
nix-pix/java-filmorate pull request #2
Opened 2023-02-17 23:38 UTC by nix-pix

2023-02-18 18:00 UTC, db-exp requested changes

2023-02-18 18:00 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int id;
"Можно лучше" Лучше сразу привыкать использовать в случае целочисленного идентификатора long как в реальных системах

2023-02-18 18:00 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private int id;
"Можно лучше" Лучше сразу привыкать использовать в случае целочисленного идентификатора long как в реальных системах

2023-02-18 18:00 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest { // использовался для 1 спринта по этому приложению
Давай удалим если не нужен больше

2023-02-18 18:00 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return null;
"Можно лучше" Старайся не возвращать null - лучше Optional

2023-02-18 18:00 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return null;
"Можно лучше" Старайся не возвращать null - лучше Optional

2023-02-18 18:00 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +//        List<User> friends = new ArrayList<>();
Давай удалим ненужный код

2023-02-18 18:00 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return null;
С другой стороны, у тебя не может получится null
если isCorrect то либо true, либо ошибка

2023-02-18 18:00 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return null;
Тут тоже - если isCorrect то либо true, либо ошибка UserNotFoundException и null не случится
Согласен?

2023-02-18 18:00 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +class UserControllerTest { // использовался для 1 спринта по этому приложению
Давай удалим если не нужен

2023-02-18 18:00 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/validator/FilmValidatorTest.java
> +//    @Test
Предлагаю удалить

2023-02-18 18:00 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/validator/UserValidatorTest.java
> +//    @Test
Предлагаю удалить

2023-02-19 11:48 UTC, nix-pix commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int id;
Ок. Переделал.

2023-02-19 11:48 UTC, nix-pix commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private int id;
Ок. Переделал.

2023-02-19 11:49 UTC, nix-pix commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest { // использовался для 1 спринта по этому приложению
Согласен. Удалил.

2023-02-19 11:49 UTC, nix-pix commented on src/test/java/ru/yandex/practicum/filmorate/validator/UserValidatorTest.java
> +//    @Test
Согласен. Удалил.

2023-02-19 11:49 UTC, nix-pix commented on src/test/java/ru/yandex/practicum/filmorate/validator/FilmValidatorTest.java
> +//    @Test
Согласен. Удалил.

2023-02-19 11:50 UTC, nix-pix commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +class UserControllerTest { // использовался для 1 спринта по этому приложению
Согласен. Удалил.

2023-02-19 11:56 UTC, nix-pix commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +//        List<User> friends = new ArrayList<>();
Согласен. Удалил.

2023-02-19 12:05 UTC, nix-pix commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return null;
Согласен. Переписал.

2023-02-19 12:05 UTC, nix-pix commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return null;
Согласен. Переписал.

2023-02-19 12:11 UTC, nix-pix commented
Все откорректировал.

2023-02-19 16:54 UTC, db-exp approved these changes

2023-02-19 19:25 UTC, merged