add-database на ревью (ТЗ-11)
nix-pix/java-filmorate pull request #3
Opened 2023-03-15 20:40 UTC by nix-pix

2023-03-16 14:42 UTC, db-exp requested changes

2023-03-16 14:42 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorageTest.java
Давай удалим если не нужен

2023-03-16 14:42 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorageTest.java
> +    public void getTopRatedFilmsTest() { //если отдельно запускать, то все ок
Давай удалим если не нужен

2023-03-16 14:42 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorageTest.java
> +    public void getFilmsTest() { //если отдельно запускать, то все ок
Давай удалим если не нужен

2023-03-16 14:42 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Friend.java
> +    private boolean status;
можно вообще не держать статус - если дружба есть, то есть и запись в бд ( у нас же нет понятия враги), а если дружбы нет - нет записи

2023-03-16 14:42 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    //private Set<Long> likes = new HashSet<>();
давай удалим

2023-03-16 14:42 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +//        filmStorage.get(filmId).getLikes().add(userStorage.get(userId).getId());
давай удалим все ненужные комментарии, тут и ниже

2023-03-16 20:35 UTC, nix-pix commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorageTest.java
> +    public void getTopRatedFilmsTest() { //если отдельно запускать, то все ок
Ок, удалил

2023-03-16 20:35 UTC, nix-pix commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorageTest.java
> +    public void getFilmsTest() { //если отдельно запускать, то все ок
Ок, удалил

2023-03-16 20:43 UTC, nix-pix commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorageTest.java
Ок, удалил

2023-03-16 20:45 UTC, nix-pix commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    //private Set<Long> likes = new HashSet<>();
Ок, удалил

2023-03-16 20:46 UTC, nix-pix commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +//        filmStorage.get(filmId).getLikes().add(userStorage.get(userId).getId());
Ок, удалил

2023-03-16 20:47 UTC, nix-pix commented on src/main/java/ru/yandex/practicum/filmorate/model/Friend.java
> +    private boolean status;
Согласен, убрал

2023-03-17 12:20 UTC, db-exp approved these changes

2023-03-17 14:59 UTC, merged